name='Aria'
internalName='aria'
voice='FEMALE'
internetAccess=True
chatgptKey="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"
commandWords=['stop','sleep','turn','play','pause','tell','increase','decrease','volume','start','exit']
explainWords=['help','sad','happy','bad','good']
queryWords=['what','why','when','where','how','tell','explain','calculate','plot','work out','give']
greetWords=['hi','yo','hello','whassup','whats up','u good?']
eolWords=['bye','ttyl','cya','gtg']
appList=[]
homeAssistAPIURL='https://home.kmnet.uk/api/conversation/process'
homeAssistAPIKEY='Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIwMTk4NGI1OWUxOGQ0ODc3OWQyZjIzYjI1ODAxZGVmZCIsImlhdCI6MTcwMDc2Nzc4OSwiZXhwIjoyMDE2MTI3Nzg5fQ.sepcLL0G-ET-vR_NCyNR2WTUqPhAqm9NeTZX68tJ2RU'
wolframAlphaAPIKEY='WX4A9R-EGQGRH4VKP'
openWeatherMapAPIURL='https://api.openweathermap.org/data/2.5/weather?'
openWeatherMapAPIKEY='8ef61edcf1c576d65d836254e11ea420'
basePath=r'C:\Users\vivaa'
userName='Vivaan Modi'
userFirstName='Vivaan'
schoolPortalURL='https://eqe.fireflycloud.net/planner/day/'